config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :partners, only: :index

  root to: "partners#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/partner.rb
# frozen_string_literal: true

class Partner < ApplicationRecord
  METERS_PER_DEGREE = 111_000 # very much simplified for this challenge

  scope :by_material, ->(material) {
    return all if material.blank?

    where "? = ANY(materials)", material
  }

  scope :ordered_by_rating_and_distance, ->(latitude = nil, longitude = nil) {
    partners = order(rating: :desc)
    return partners unless latitude.present? && longitude.present?

    lat_distance  = "((latitude  - #{latitude})  * #{METERS_PER_DEGREE})"
    long_distance = "((longitude - #{longitude}) * #{METERS_PER_DEGREE})"
    distance = "SQRT(POWER(#{lat_distance}, 2) + POWER(#{long_distance}, 2)) / 1000.0"

    partners
      .select("partners.*, #{distance} as distance")
      .where("operating_radius >= #{distance}")
      .order(:distance)
  }

  def self.material_options
    distinct.pluck(:materials).flatten.uniq.sort
  end

  def distance_km
    return unless (distance = self[:distance])

    distance.round(1)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/partners_controller.rb
# frozen_string_literal: true

class PartnersController < ApplicationController
  def index
    @partners = Partner
                .by_material(params[:material])
                .ordered_by_rating_and_distance(params[:latitude], params[:longitude])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title FlooringPartnerMatch
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'

  body
    .page-content = yield

app/views/partners/index.html.slim
h1.partner-heading = link_to "Flooring Partners", root_path

.search
  = form_tag partners_path, method: :get, class: "search__form" do
    .search__latitude
      = label_tag :latitude, "Your location's latitude"
      =< number_field_tag :latitude, params[:latitude], step: 0.000000000000001

    .search__material
      = label_tag :material
      =< select_tag :material, options_for_select(Partner.material_options, params[:material]), include_blank: true
    .search__longitude
      = label_tag :longitude, "Your location's longitude"
      =< number_field_tag :longitude, params[:longitude], step: 0.000000000000001

    = submit_tag "Search"

  .customer-info
    h2 Additional information

    .search__square_meters
      = label_tag :square_meters
      =< number_field_tag :square_meters, params[:square_meters]
    .search__phone
      = label_tag :phone
      =< text_field_tag :phone, params[:phone]

.partners
  - @partners.each do |partner|
    .partner
      .partner__name
        span.partner__attribute-name Company name:
        span =< partner.name
      .partner__materials
        span.partner__attribute-name Materials:
        span =< partner.materials.join(", ")
      .partner__radius
        span.partner__attribute-name Operating radius:
        span =< partner.operating_radius
      .partner__latitude
        span.partner__attribute-name Latitude:
        span =< partner.latitude
      .partner__longitude
        span.partner__attribute-name Longitude:
        span =< partner.longitude
      .partner__rating
        span.partner__attribute-name Rating:
        span =< partner.rating

      - if partner.distance_km
        .partner__distance
          span.partner__attribute-name Distance:
          span
            =<> partner.distance_km
            |km